### ISSUE TITLE
[Dev Branch] How to use the dump models to folder feature for propcombiner?

### ISSUE THREAD

**Issue by WereTech** [TeamSpen210/HammerAddons#214]
I've tried looking through the code of what was added for this, but I can't find where to add a path for it to dump to, does this need to be added as an arg or change --propcombine to accept a path that it can dump to?

**Comment by TeamSpen210** [comment]
It's a [config option in `srctools.vdf`](https://github.com/TeamSpen210/HammerAddons/blob/253f4c17eade4d1e987eb5a0e55ef6b18417625f/src/hammeraddons/config.py#L375) - set it, then the sources for the models will be left there. You'll want to copy them elsewhere and change the model name, since that folder is also going to be cleared after each compile. I should mention that.
