### ISSUE TITLE
Alien Swarm: Reactive Drop - Parallax-Corrected Cubemaps

### ISSUE THREAD

**Issue by BenLubar** [TeamSpen210/HammerAddons#230]
Hi! Static prop combining is something I've wanted to add to AS:RD for quite a while, and until now I've thought it would require us to port the SDK 2013 compilers over to our engine version, but in just a little bit of fiddling around with compiling Landing Bay, I've managed to get it to combine props with your postcompiler. (And I've also managed to make the bsp file five times its normal size, but that's my problem, not yours!)

Another thing I want to add is parallax-corrected cubemaps, which requires a change to the shader code (which I have already done and is going to be released in two days) and a change to vbsp to make it output materials with the required matrix computed in them (which I have not yet done).

We don't have any maps set up with parallax cubemap bounds yet, so we're completely flexible with how it's going to be defined in Hammer. For example, it could be a `comp_` entity that postcompiler strips out and uses to modify the vmt.

We're using mostly what's described on the Valve Developer wiki, with the sole addition of `$envmapparallax`, which must be set to 1 in the VMT. (There was an issue with getting Alien Swarm's version of materialsystem to tell me whether the matrices were defined or not.)

https://developer.valvesoftware.com/wiki/Parallax_Corrected_Cubemaps#The_Code

If this is something you'd be willing to add to postcompiler.exe, I can try my hand at writing a pull request for it if you tell me what you want it to look like in the FGD.

**Comment by TeamSpen210** [comment]
I'd certainly be willing to add this as a feature, it's something the postcompiler could definitely help with. First thing to do would be to edit `unify_fgd.py`, add `ASWRD` to the list of tags so that FGD changes can be restricted to your mod. I assume you've changed other things from base ASW, might as well do that first. For the parallax cubemaps, it wouldn't necessarily need to be built into the EXE, it can just be another transform that you could either ship with just your mod, or include in this repo. 

Either way, the ent probably should be similar to `comp_propcombine_set`, with a min/max pair of keyvalues. I suppose the tricky thing would be matching the new ent to the `env_cubemap` - we can't modify that ent, since it's long been deleted by VBSP. Reading the cubemap locations from the BSP is easy though. With a bit of work we could alternatively make it a brush entity, but that involves reconstructing the orientation from the faces, and it'd leave some remmnants from the brush data that isn't easy to clean up.
