### ISSUE TITLE
`OnFizzled` output is not present on `prop_weighted_cube` but is somehow present on `prop_floor_button`

### ISSUE THREAD

**Issue by DrPeeper228** [TeamSpen210/HammerAddons#232]
Look at the name(i am not the only one who has the issue, my friend also has it)

**Comment by TeamSpen210** [comment]
Hmm weird that it’s not on cubes. It should be on buttons, the output is in fact available and functional on all model-based entities. Though obviously it’d be rather unlikely for a button to end up in a situation where it can be fizzled.

**Comment by DrPeeper228** [comment]
oh, but yeah it's strange it isn't on cubes

**Comment by The1stWii2** [comment]
It's because `prop_floor_button` inherits **`OnFizzled`** from `BaseEntityAnimating`, which isn't a base for `prop_weighted_cube`. The handful of other entities which have **`OnFizzled`** and *don't* inherit it from `BaseEntityAnimating` all manually define it.
It might be a good idea to add a definition to `BaseEntityPhysics`, of which, it seems, *most* other model-based entities inherit from.
![inheritance](https://github.com/TeamSpen210/HammerAddons/assets/109736937/5ab5607f-f25d-47e1-b22c-1b3c55387133)

**Comment by TeamSpen210** [comment]
Ahh whoops, need to check why BasePropPhysics doesn't inherit from BaseEntityAnimating. It would in code.
