### ISSUE TITLE
point_devshot_camera rotates incorrectly

### ISSUE THREAD

**Issue by StefanH-AT** [TeamSpen210/HammerAddons#98]
Image shows it

![image](https://user-images.githubusercontent.com/31664665/90299139-49ed4000-de95-11ea-9d22-b867164aa42f.png)

**Comment by Fennecai** [comment]
also happens for point_viewcontrol in fact.

**Comment by Luke18033** [comment]
I looked into this, there are two problems with the frustum helper which combine to cause this issue. I'll use `frustum(90, 16, 256, 255 255 255 10, -1)` as an example configuration.
- The helper expects all of its parameters except the last to be keyvalue names, rather than direct values. This means for the above example it's going to attempt to read those values from keyvalues named `90`, `16`, `256`, and `255` (see below) - this can be proven if they are added with SmartEdit off.
- Hammer is actually interpreting the color as 4 separate parameters, despite there being no commas between them. This results in the green component of the color being used as the pitch scale, with the blue and (alpha?) components and the *real* pitch scale going entirely unused. With the above example, this means the pitch scale is actually going to be `255`, not `-1` as intended. (This is also why turrets don't change their frustum pitch at all - the color is set to `255 0 0`, so the pitch scale is read as 0.)

**Comment by Luke18033** [comment]
The only way to work around this would be to add fake read-only keyvalues which are used for the display of the helper. What I'm not sure about is how these should appear in Hammer, there are three main methods I thought of:

- The easiest option would be to add normal read-only keyvalues containing each of the properties, but that clutters up the keyvalue list with ones that are mostly useless.
- I found a trick that lets you make a keyvalue invisible, by making it `choices` type and setting its name and default value name to a single space. But this still adds empty space at the bottom of the keyvalues list.
- A modified version of the above trick can be used to hide the values inside the line dividers, but there's only a limited number of those per entity, and since you can't redefine a keyvalue as a different type it means the original line divider also needs to be changed to an empty `choices` list.

I'm not sure which of these methods would be best, or if it's even worth it to try and hide these fake keyvalues at all.

**Comment by TeamSpen210** [comment]
Interesting.

**Comment by Luke18033** [comment]
Yeah. Does it automatically remove `!engine` keyvalues?

**Comment by TeamSpen210** [comment]
It doesn't, but you can add an extra transform which goes and does this.
